---
- name: Creates cache path
  ansible.builtin.file:
    path: "{{ cache_path }}"
    state: directory
  delegate_to: localhost

- name: Check if nix-portable exists
  ansible.builtin.stat:
    path: "{{ nix_portable }}"
  register: stat_nix_portable
  delegate_to: localhost

- name: Fetch GitHub release for nix-portable
  uri:
    url: "https://api.github.com/repos/DavHau/nix-portable/releases/tags/v{{ nix_portable_version }}"
    return_content: true
  register: json_reponse
  delegate_to: localhost
  when: not stat_nix_portable.stat.exists

- name: Download nix-portable
  get_url:
    url: "{{ json_reponse.json.assets[0].browser_download_url }}"
    dest: "{{ nix_portable }}"
    mode: "0755"
  delegate_to: localhost
  when: not stat_nix_portable.stat.exists

- name: Check if nix-wrapper exists
  ansible.builtin.stat:
    path: "{{ nix_wrapper }}"
  register: stat_nix_wrapper
  delegate_to: localhost

- name: Install nix wrapper
  ansible.builtin.template:
    src: templates/nix-wrapper.j2
    dest: "{{ nix_wrapper }}"
    mode: "0755"
  delegate_to: localhost
  when: not stat_nix_wrapper.stat.exists
