---
#- debug:
#    msg: "{{ exported_vars }}"

- name: Create temporary file for ansible variables
  tempfile:
    state:  file
    suffix: .json
  register: ansible_json_vars
  delegate_to: localhost

- name: Write variables to file
  ansible.builtin.template:
    src: templates/json.j2
    dest: "{{ ansible_json_vars.path }}"
  delegate_to: localhost
  when: not ansible_check_mode

- block:
  - name: Deploy "{{ flake_url }}" to "{{ target_host }}"
    ansible.builtin.shell: |
      env ANSIBLE_JSON={{ ansible_json_vars.path | quote }} {{ nix_wrapper }} nix run nixpkgs#nixos-rebuild -- --use-substitutes --flake "{{ flake_dir }}#{{ flake_target }}" "switch" --impure --target-host "{{ target_host }}" --show-trace
    delegate_to: localhost
    register: nixos_rebuild
    when: not ansible_check_mode
  rescue:
   - fail:
       msg: "NixOS Deployment {{ flake_url }} to {{ target_host }} failed"
     delegate_to: localhost
     name: >
       NixOS Deployment {{ flake_url }} to {{ target_host }} failed:
       {{ nixos_rebuild.stderr }}
