---
#- debug:
#    msg: "{{ exported_vars }}"

- name: Creates state directory
  file:
    path: "{{ loc_base }}"
    state: directory
  delegate_to: localhost

- name: Write variables to file
  ansible.builtin.template:
    src: templates/json.j2
    dest: "{{ loc_json }}"
    mode: "0655"
  delegate_to: localhost

- name: Write deploy script to file
  ansible.builtin.template:
    src: templates/script.j2
    dest: "{{ loc_script }}"
    mode: "0755"
  delegate_to: localhost

- block:
  - name: Deploy "{{ flake_url }}" to "{{ target_host }}"
    ansible.builtin.shell: "{{ loc_script }}"
    delegate_to: localhost
    register: nixos_rebuild
    when: not ansible_check_mode
  rescue:
   - fail:
       msg: "NixOS Deployment {{ flake_url }} to {{ target_host }} failed"
     delegate_to: localhost
     name: >
       NixOS Deployment {{ flake_url }} to {{ target_host }} failed:
       {{ nixos_rebuild.stderr }}
