---
- name: Deploy "{{ flake_url }}" to "{{ target_host }}"
  ansible.builtin.shell: |
    env ANSIBLE_JSON={{ exported_vars | to_json | quote }} {{ nix_wrapper }} nix run nixpkgs#nixos-rebuild -- --flake "{{ flake_dir }}#{{ flake_target }}" "switch" --impure --target-host "{{ target_host }}"
  delegate_to: localhost
