---
- name: Deploy "{{ flake_url }}" to "{{ target_host }}"
  ansible.builtin.shell: |
    {{ nix_wrapper }} nix run nixpkgs#nixos-rebuild -- --flake "{{ flake_dir }}#{{ flake_target }}" "switch" --target-host "{{ target_host }}"
  delegate_to: localhost
